version: "3.9"
services:
  api:
    build:
      context: .
      dockerfile: build/api/Dockerfile.dev
    container_name: api
    depends_on:
      pgsql:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - target: 8080
        published: 8080
        protocol: TCP
        mode: host
    stdin_open: true
    tty: true
    volumes:
      - ./:/go/src

  pgsql:
    build:
      context: .
      dockerfile: build/postgres/Dockerfile
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      PGUSER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: stuhub
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/pgsql
        volume:
          nocopy: true

volumes:
  db-data:
