// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameActivity = "activity"

// Activity mapped from table <activity>
type Activity struct {
	Pkid       int64     `gorm:"column:pkid;type:bigint;primaryKey;autoIncrement:true" json:"pkid"`
	UserPkid   int64     `gorm:"column:user_pkid;type:bigint;not null" json:"user_pkid"`
	ActionCode string    `gorm:"column:action_code;type:character varying(100);not null" json:"action_code"`
	CreatedAt  time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	Snapshot   string    `gorm:"column:snapshot;type:jsonb;not null;default:{}" json:"snapshot"`
}

// TableName Activity's table name
func (*Activity) TableName() string {
	return TableNameActivity
}
