// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNamePagePermission = "page_permissions"

// PagePermission mapped from table <page_permissions>
type PagePermission struct {
	Pkid                       int64  `gorm:"column:pkid;type:bigint;primaryKey;autoIncrement:true" json:"pkid"`
	UserPkid                   int64  `gorm:"column:user_pkid;type:bigint;not null" json:"user_pkid"`
	Roles                      string `gorm:"column:roles;type:character varying(255)[];not null;default:{}" json:"roles"`
	IsInheritPermission        bool   `gorm:"column:is_inherit_permission;type:boolean;not null" json:"is_inherit_permission"`
	GeneralPermissions         string `gorm:"column:general_permissions;type:character varying(255)[];not null;default:{}" json:"general_permissions"`
	IsGeneralPermissionEnabled bool   `gorm:"column:is_general_permission_enabled;type:boolean;not null" json:"is_general_permission_enabled"`
}

// TableName PagePermission's table name
func (*PagePermission) TableName() string {
	return TableNamePagePermission
}
