// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePagePermissionRequestLog = "page_permission_request_log"

// PagePermissionRequestLog mapped from table <page_permission_request_log>
type PagePermissionRequestLog struct {
	Pkid      int64     `gorm:"column:pkid;type:bigint;primaryKey;autoIncrement:true" json:"pkid"`
	PagePkid  int64     `gorm:"column:page_pkid;type:bigint;not null" json:"page_pkid"`
	UserPkid  *int64    `gorm:"column:user_pkid;type:bigint" json:"user_pkid"`
	Email     string    `gorm:"column:email;type:character varying(255);not null" json:"email"`
	CreatedAt time.Time `gorm:"column:created_at;type:timestamp with time zone;not null;default:now()" json:"created_at"`
	Status    string    `gorm:"column:status;type:character varying(20);not null;default:pending" json:"status"`
}

// TableName PagePermissionRequestLog's table name
func (*PagePermissionRequestLog) TableName() string {
	return TableNamePagePermissionRequestLog
}
