// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameRelatePageActivity = "relate_page_activity"

// RelatePageActivity mapped from table <relate_page_activity>
type RelatePageActivity struct {
	Pkid         int64 `gorm:"column:pkid;type:bigint;primaryKey;autoIncrement:true" json:"pkid"`
	PagePkid     int64 `gorm:"column:page_pkid;type:bigint;not null;uniqueIndex:unique_relate_page_activity_idx,priority:1" json:"page_pkid"`
	ActivityPkid int64 `gorm:"column:activity_pkid;type:bigint;not null;uniqueIndex:unique_relate_page_activity_idx,priority:2" json:"activity_pkid"`
}

// TableName RelatePageActivity's table name
func (*RelatePageActivity) TableName() string {
	return TableNameRelatePageActivity
}
